In [49]:
import pandas as pd
import numpy as np
from sklearn import datasets
from sklearn import metrics
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder

In [105]:
data = pd.read_excel(r"C:\Users\user\OneDrive\Desktop\Gymapp\dataGym.xlsx")
data.head()

Age  Height  weight  BMI            Class  \
0   31     4.1      86   40  Extremely obese   
1   23     4.1      91   42  Extremely obese   
2   58     4.1      95   44  Extremely obese   
3   28     4.1     100   46  Extremely obese   
4   48     4.1     104   48  Extremely obese   

                                          Prediction  
0  Extremely obese--normal exercise+yoga+heavy di...  
1  Extremely obese--normal exercise+yoga+heavy di...  
2  Extremely obese--normal exercise+yoga+heavy di...  
3  Extremely obese--normal exercise+yoga+heavy di...  
4  Extremely obese--normal exercise+yoga+heavy di...

In [5]:
#data['weight'] = data['weight']*2.2

In [106]:
data['Class'] = data['Class'].replace('Healthy\xa0','Healthy').replace('EXtremely obese','Extremely obese').replace('Extremely obese','Extremelyobese')

In [107]:
data['Class'].unique()

array(['Extremelyobese', 'Healthy', 'Obese', 'Overweight', 'Under weight'],
      dtype=object)

In [108]:
data['Prediction'].unique()

array(['Extremely obese--normal exercise+yoga+heavy dite control+TIPS ->Obese',
       'Healthy--fitness+protine+simple dite',
       'Obese--slow lean+protine+full dite ->Overweight',
       'Overweight--lean+cardio+protine+normal dite ->Healthy',
       'Under weight--protines+carbs+normal weights ->Healthy'],
      dtype=object)

In [109]:
l = ['Extremely obese--normal exercise+yoga+heavy dite control+TIPS ->Obese',
       'Healthy--fitness+protine+simple dite',
       'Obese--slow lean+protine+full dite ->Overweight',
       'Overweight--lean+cardio+protine+normal dite ->Healthy',
       'Under weight--protines+carbs+normal weights ->Healthy']
a = ['Extreme Calorie deficiet+ no cheat days +Cardio+ Regular Gym + Patience','Regular gym + Calorie surplus + keep it up',
     'Calorie deficiet+ Cardio+ Regular Gym+ Patience','Calorie deficiet+ Cardio+ Regular Gym', 'Calorie Surplus + Regular gym' ]
j = 0
for i in l:
    data['Prediction'] = data['Prediction'].replace(l[j],a[j])
    j+=1

In [110]:
data['Prediction'].unique()

array(['Extreme Calorie deficiet+ no cheat days +Cardio+ Regular Gym + Patience',
       'Regular gym + Calorie surplus + keep it up',
       'Calorie deficiet+ Cardio+ Regular Gym+ Patience',
       'Calorie deficiet+ Cardio+ Regular Gym',
       'Calorie Surplus + Regular gym'], dtype=object)

In [111]:
data['Prediction'].value_counts()

Calorie deficiet+ Cardio+ Regular Gym+ Patience                            281
Calorie Surplus + Regular gym                                              248
Regular gym + Calorie surplus + keep it up                                 232
Extreme Calorie deficiet+ no cheat days +Cardio+ Regular Gym + Patience    216
Calorie deficiet+ Cardio+ Regular Gym                                      199
Name: Prediction, dtype: int64

In [112]:
data['Class'].value_counts()

Obese             281
Under weight      248
Healthy           232
Extremelyobese    216
Overweight        199
Name: Class, dtype: int64

In [113]:
data.head()

Age  Height  weight  BMI           Class  \
0   31     4.1      86   40  Extremelyobese   
1   23     4.1      91   42  Extremelyobese   
2   58     4.1      95   44  Extremelyobese   
3   28     4.1     100   46  Extremelyobese   
4   48     4.1     104   48  Extremelyobese   

                                          Prediction  
0  Extreme Calorie deficiet+ no cheat days +Cardi...  
1  Extreme Calorie deficiet+ no cheat days +Cardi...  
2  Extreme Calorie deficiet+ no cheat days +Cardi...  
3  Extreme Calorie deficiet+ no cheat days +Cardi...  
4  Extreme Calorie deficiet+ no cheat days +Cardi...

In [104]:
#data['Class'] = LabelEncoder().fit_transform(data['Class'])

In [114]:
data['Class'].unique()

array(['Extremelyobese', 'Healthy', 'Obese', 'Overweight', 'Under weight'],
      dtype=object)

In [115]:
X =data.iloc[:,:3]
X.head()

Age  Height  weight
0   31     4.1      86
1   23     4.1      91
2   58     4.1      95
3   28     4.1     100
4   48     4.1     104

In [116]:
y = data.iloc[:,4]
y.head()

0    Extremelyobese
1    Extremelyobese
2    Extremelyobese
3    Extremelyobese
4    Extremelyobese
Name: Class, dtype: object

In [117]:
#splitting pf data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2)

In [118]:
X_test.head()

Age  Height  weight
321   58    5.11      95
751   37    6.10      45
189   53    5.00      45
869   44    6.20     100
943   32    6.40     132

In [119]:
y_test.head()

321      Overweight
751    Under weight
189         Healthy
869      Overweight
943           Obese
Name: Class, dtype: object

In [120]:
model_GYM = RandomForestClassifier(n_estimators=20)
model_GYM.fit(X_train, y_train.values.ravel())

RandomForestClassifier(n_estimators=20)

In [121]:
# make predictions
expected = y_test
predicted = model_GYM.predict(X_test)

In [122]:
# summarize the fit of the model
#Correction
print(metrics.classification_report(expected, predicted))
print(metrics.confusion_matrix(expected, predicted))

                precision    recall  f1-score   support

Extremelyobese       0.84      0.95      0.89        38
       Healthy       0.75      0.87      0.80        47
         Obese       0.80      0.80      0.80        59
    Overweight       0.72      0.55      0.62        42
  Under weight       0.94      0.88      0.91        50

      accuracy                           0.81       236
     macro avg       0.81      0.81      0.80       236
  weighted avg       0.81      0.81      0.81       236

[[36  0  2  0  0]
 [ 0 41  0  3  3]
 [ 6  0 47  6  0]
 [ 1  8 10 23  0]
 [ 0  6  0  0 44]]
