In [1]:
import pandas as pd
import numpy as np
from sklearn import datasets
from sklearn import metrics
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder

In [2]:
data = pd.read_excel(r"C:\Users\user\Downloads\bepec\phase-2\Supervised learning\Gymapp\dataGYM.xlsx")
data.head()

Age    Height  Weight        BMI       Class  \
0   75  1.498603     115  51.206447       Obese   
1   37  1.549403      72  29.991878  Overweight   
2   31  1.498603      77  34.286056       Obese   
3   26  1.549403     112  46.654032       Obese   
4   68  1.752604     106  34.509488       Obese   

                                  Prediction  
0  Strength Training + Cardio + HardCoreDiet  
1      Normal Diet + Strength Train + Cardio  
2  Strength Training + Cardio + HardCoreDiet  
3  Strength Training + Cardio + HardCoreDiet  
4  Strength Training + Cardio + HardCoreDiet

In [6]:
data['Class'] = LabelEncoder().fit_transform(data['Class'])

In [7]:
data.head()

Age    Height  Weight        BMI  Class  \
0   75  1.498603     115  51.206447      1   
1   37  1.549403      72  29.991878      2   
2   31  1.498603      77  34.286056      1   
3   26  1.549403     112  46.654032      1   
4   68  1.752604     106  34.509488      1   

                                  Prediction  
0  Strength Training + Cardio + HardCoreDiet  
1      Normal Diet + Strength Train + Cardio  
2  Strength Training + Cardio + HardCoreDiet  
3  Strength Training + Cardio + HardCoreDiet  
4  Strength Training + Cardio + HardCoreDiet

In [20]:
X =data.iloc[:,:3]
X.head()

Age    Height  Weight
0   75  1.498603     115
1   37  1.549403      72
2   31  1.498603      77
3   26  1.549403     112
4   68  1.752604     106

In [21]:
y = data.iloc[:,5:]
y.head()

Prediction
0  Strength Training + Cardio + HardCoreDiet
1      Normal Diet + Strength Train + Cardio
2  Strength Training + Cardio + HardCoreDiet
3  Strength Training + Cardio + HardCoreDiet
4  Strength Training + Cardio + HardCoreDiet

In [29]:
#splitting pf data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2)

In [30]:
X_test.head()

Age    Height  Weight
82    39  1.676403     103
135   69  1.219202     111
53    63  1.752604      99
130   49  1.600203      88
36    57  1.219202      88

In [31]:
y_test.head()

Prediction
82   Strength Training + Cardio + HardCoreDiet
135  Strength Training + Cardio + HardCoreDiet
53   Strength Training + Cardio + HardCoreDiet
130  Strength Training + Cardio + HardCoreDiet
36   Strength Training + Cardio + HardCoreDiet

In [32]:
model_GYM = RandomForestClassifier(n_estimators=20)
model_GYM.fit(X_train, y_train.values.ravel())

RandomForestClassifier(n_estimators=20)

In [33]:
# make predictions
expected = y_test
predicted = model_GYM.predict(X_test)

In [34]:
# summarize the fit of the model
#Correction
print(metrics.classification_report(expected, predicted))
print(metrics.confusion_matrix(expected, predicted))

                                           precision    recall  f1-score   support

    Normal Diet + Strength Train + Cardio       0.00      0.00      0.00         4
Strength Training + Cardio + HardCoreDiet       0.86      1.00      0.92        24
             StrengthTrain +  Simple diet       1.00      1.00      1.00         2

                                 accuracy                           0.87        30
                                macro avg       0.62      0.67      0.64        30
                             weighted avg       0.75      0.87      0.81        30

[[ 0  4  0]
 [ 0 24  0]
 [ 0  0  2]]


C:\Users\user\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
